apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-mlnx
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlnx_rdma
spec:
  config: '{
  "cniVersion":"0.3.1",
  "type":"multus-shim",
  "clusterNetwork":"/etc/cni/net.d/10-calico.conflist"
}'
