apiVersion: v1
kind: Service
metadata:  
  name: ntopng-service
  namespace: production
  labels:
    run: ntopng
spec:
  selector:    
    app: ntopng
  type: LoadBalancer
  ports: 
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
